version: "3.3"
services:
  quickappdb:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      container_name: quickappdb 
      user: root
      networks:
        - appnet
      ports:
        - "1433:1433"
      environment:
        - SA_PASSWORD=DevOps@123
        - ACCEPT_EULA=Y
  app:
      image: "quickapp"
      networks:
        - appnet
      container_name: angular_app
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - quickappdb
      restart: always
      ports:
        - "80:5000"  
        - "443:5001"
      environment:
        - ASPNETCORE_URLS=https://+:5001;http://+:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=B@oL0ng@123456
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Server=quickappdb;Database=QuickApp1;USER=sa;Password=DevOps@123;MultipleActiveResultSets=true
networks:
  appnet:
    # name: appnet
    # external: false